version: "3"
services:
  opengauss:
    image: lsqtzj/openeuler_open_gauss:${OPEN_GAUSS_VERSION}
    build:
      context: .
      dockerfile: openeuler_open_gauss/Dockerfile
    #restart: always
    container_name: opengauss
    hostname: opengauss
    networks:
      gauss:
        ipv4_address: 10.8.0.10
    ports:
      - 5432:5432
      - 8980:80
      - 8008:8008
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      RUN_MODE: "standard"  # 主机模式 "master"/"slave"/"standard" | patroni 服务版本只用于首次设置，Leader 机由patroni进行控制
      GAUSS_USER: ${GAUSS_USER}   # 远程管理员
      GAUSS_PASSWORD: ${GAUSS_PASSWORD} # 密码
      GAUSS_DATABASE: test # 初始化数据库 \c 切换数据库 要输入密码，所以加这个参数用来创建数据库
    volumes:
      - ./data/opengauss/data:/opt/software/openGauss/data    
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql # 初始化数据表

  pgadmin4:
    image: lsqtzj/openeuler_pgadmin4
    restart: always
    container_name: pgadmin4
    hostname: pgadmin4
    networks:
      gauss:
        ipv4_address: 10.8.0.18
    ports:
      - 9980:80
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # pgadmin4管理员
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}         # pgadmin4管理员密码
    volumes:
      - ./data/pgadmin4/data:/var/lib/pgadmin4
      - ./data/pgadmin4/logs:/var/log/pgadmin4
    depends_on:
      - master

networks:
  gauss:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1