version: "3"
services:  
  master:
    image: lsqtzj/openeuler_open_gauss:${OPEN_GAUSS_VERSION}
    restart: always
    container_name: master
    hostname: master
    networks:
      gauss:
        ipv4_address: 10.8.0.10
    ports:
      - 15432:5432
      - 8980:80
      - 8008:8008
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      NODE_NAME: datanode1
      RUN_MODE: "master"  # 主机模式 "master"/"slave" | patroni 服务版本只用于首次设置，Leader 机由patroni进行控制
      GAUSS_USER: ${GAUSS_USER}   # 远程管理员
      GAUSS_PASSWORD: ${GAUSS_PASSWORD} # 密码
      HOST_NAMES: slave01,slave02 # 主机列表
    extra_hosts:
      - "master:10.8.0.10"
      - "slave01:10.8.0.11"
      - "slave02:10.8.0.12"
      - "pgadmin4:10.8.0.18"
      - "haproxy:10.8.0.19"

  slave01:
    image:  lsqtzj/openeuler_open_gauss:${OPEN_GAUSS_VERSION}
    restart: always
    container_name: slave01
    hostname: slave01
    networks:
      gauss:
        ipv4_address: 10.8.0.11
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      GAUSS_USER: ${GAUSS_USER}
      GAUSS_PASSWORD: ${GAUSS_PASSWORD}
      NODE_NAME: datanode2
      RUN_MODE: "slave"
      HOST_NAMES: master,slave02
    extra_hosts:
      - "master:10.8.0.10"
      - "slave01:10.8.0.11"
      - "slave02:10.8.0.12"
      - "pgadmin4:10.8.0.18"
      - "haproxy:10.8.0.19"
    depends_on:
      - master

  slave02:
    image:  lsqtzj/openeuler_open_gauss:${OPEN_GAUSS_VERSION}
    restart: always
    container_name: slave02
    hostname: slave02
    networks:
      gauss:
        ipv4_address: 10.8.0.12
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      GAUSS_USER: ${GAUSS_USER}
      GAUSS_PASSWORD: ${GAUSS_PASSWORD}
      NODE_NAME: datanode3
      RUN_MODE: "slave"
      HOST_NAMES: master,slave01
    extra_hosts:
      - "master:10.8.0.10"
      - "slave01:10.8.0.11"
      - "slave02:10.8.0.12"
      - "pgadmin4:10.8.0.18"
      - "haproxy:10.8.0.19"
    depends_on:
      - master
  
  haproxy:
    image: lsqtzj/openeuler_haproxy:${HAPROXY_VERSION}
    restart: always
    container_name: haproxy
    hostname: haproxy
    networks:
      gauss:
        ipv4_address: 10.8.0.19
    ports:
      - 7000:7000
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # pgadmin4管理员
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}         # pgadmin4管理员密码
      ips: "10.8.0.10,10.8.0.11,10.8.0.12"
      ports: "5432,5432,5432"
    extra_hosts:
      - "master:10.8.0.10"
      - "slave01:10.8.0.11"
      - "slave02:10.8.0.12"
      - "pgadmin4:10.8.0.18"
      - "haproxy:10.8.0.19"
    depends_on:
      - master

  pgadmin4:
    image:  lsqtzj/openeuler_pgadmin4
    restart: always
    container_name: pgadmin4
    hostname: pgadmin4
    networks:
      gauss:
        ipv4_address: 10.8.0.18
    ports:
      - 9980:80
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      PGADMIN_DEFAULT_EMAIL: admin@domain.com # pgadmin4管理员
      PGADMIN_DEFAULT_PASSWORD: admin         # pgadmin4管理员密码
    extra_hosts:
      - "master:10.8.0.10"
      - "slave01:10.8.0.11"
      - "slave02:10.8.0.12"
      - "pgadmin4:10.8.0.18"
      - "haproxy:10.8.0.19"
    depends_on:
      - master

networks:
  gauss:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1